#!/bin/sh

#############################################################
# Generic configuration that applies to all shells
#############################################################

###################
# Set vi as our default command line editor
export EDITOR='vi'

###################
# Load paths and environment variables
source ~/.shellactivities
if [ -e ~/.shelllocal ]; then
    source ~/.shelllocal
fi
source ~/.shellpaths
source ~/.shellaliases
