#!/bin/sh

#################################
# Simple program name / common args shortening
#
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -lha'
alias la='ls -A'
alias l5='ls -lhtra | tail -5'
alias pp='ps -eLfww'
alias lessc='less -R' # Lets color escape sequences carry through to less
alias morec='more -R'
alias lesscolor='less -R'
alias morecolor='more -R'
alias st='/opt/sublime_text/sublime_text'
alias tree='tree -C'
alias web='google-chrome'

alias _="sudo"

#################################
# git
alias g='git'
alias gra='for file in `g st | cut -d" " -f3`; do g co -- $file; done;'

#################################
# Utilities

# Cat the oracle tns file
alias show.tns='cat $ORACLE_HOME/network/admin/tnsnames.ora'
alias sql='rlwrap -c sqlplus $@'
alias hexdumpfile='od -h'
# Lists the ten most used commands.
alias history.stat="history 0 | awk '{print \$2}' | sort | uniq -c | sort -n -r | head"
# Show network connections
# Often useful to prefix with SUDO to see more system level network usage
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias network.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"
alias network.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

# Files used, anywhere on the filesystem
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files being opened
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files in use in the Users directory
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

#################################
# Common Curl Commands
alias cujs='curl -H "Accept: application/json" -H "Content-Type: application/json"'

#################################
# Location jumps

alias to.erx='cd /data/erx'
alias to.tools='cd /data/tools'
alias to.trunk='cd /data/erx/source/trunk'
alias to.build='cd /data/erx/build/current'
alias to.boss='cd /data/tools/jboss-as-7.1.1.Final'
alias to.ehm='cd /data/git/sparkea'
alias to.dev='cd /data/git/dev'

#################################
# docker
#alias docker="sudo docker"
alias d="docker"
# Get latest container ID
alias dl="docker ps -l -q"
# Get container process
alias dps="docker ps"
# Get process included stop container
alias dpa="docker ps -a"
# Get images
alias di="docker images"
# Get container IP
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"
# Run deamonized container, e.g., $dkd base /bin/echo hello
alias dkd="docker run -d -P"
# Run interactive container, e.g., $dki base /bin/bash
alias dki="docker run -i -t -P"
# Stop all containers
dstop() { docker stop $(docker ps -a -q);}
# Remove all containers
drm() { docker rm $(docker ps -a -q); }
# Stop and Remove all containers
alias drmf='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
alias drmd='docker rmi $(docker images -f "dangling=true" -q)'
# Remove all images
dri() { docker rmi $(docker images -q); }
# Dockerfile build, e.g., $dbu tcnksm/test 
dbu() { docker build -t=$1 .; }
# Show all alias related docker
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort;}

#################################
# Vagrant Aliases
alias v="vagrant"
alias vup="vagrant up"
alias vh="vagrant halt"
alias vs="vagrant suspend"
alias vr="vagrant resume"
alias vrl="vagrant reload"
alias vssh="vagrant ssh"
alias vst="vagrant status"
alias vp="vagrant provision"
alias vdstr="vagrant destroy"
# requires vagrant-list plugin
alias vl="vagrant list"
# requires vagrant-hostmanager plugin
alias vhst="vagrant hostmanager"

#################################
# Gulp Aliases
alias gus='gulp server | ./node_modules/.bin/bunyan -o short'
alias gut='gulp test'
alias gub='gulp build'

#################################
# Gradle Aliases
alias gw='gradle'
