#!/bin/sh

export SVN_EDITOR=vi
export GDK_NATIVE_WINDOWS=1

export PS1="\
[\[$prompt_device_color\]\h\[$prompt_reset\]][\[$prompt_direct_color\]\w\[$prompt_reset\]]\
\$( is_on_git && \
  echo -n \"[\[$prompt_git_master_color\]\$(get_git_info_master)\" && \
  echo -n \"\[$prompt_git_branch_color\]\$(get_git_info_branch)\" && \
  echo -n \"\[$prompt_git_status_color\]\$(get_git_status)\" && \
  echo -n \"\[$prompt_git_progress_color\]\$(get_git_progress)\" && \
  echo -n \"\[$prompt_preposition_color\]]\")\[$prompt_reset\]\
$(__docker_machine_ps1)$ "

case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

export JAVA_HOME=/opt/tools/java/current
export ANT_HOME=/opt/tools/apache-ant-1.9.6
export ORACLE_HOME=/opt/tools/oracle/12_1
export GRADLE_HOME=/opt/tools/gradle-3.0

export SQLPATH=$ORACLE_HOME/bin
export LD_LIBRARY_PATH=$ORACLE_HOME/bin

export CATALINA_BASE=/opt/deploy/cps/config/tomcat
export REDIS_HOME=/opt/tools/redis-3.2.3/src
export PATH=$REDIS_HOME:$PATH
