#!/bin/sh

export SVN_EDITOR=vi
export GDK_NATIVE_WINDOWS=1

export PS1="\
[\[$prompt_device_color\]\h\[$prompt_reset\]][\[$prompt_direct_color\]\w\[$prompt_reset\]]\
\$( is_on_git && \
  echo -n \"[\[$prompt_git_master_color\]\$(get_git_info_master)\" && \
  echo -n \"\[$prompt_git_branch_color\]\$(get_git_info_branch)\" && \
  echo -n \"\[$prompt_git_status_color\]\$(get_git_status)\" && \
  echo -n \"\[$prompt_git_progress_color\]\$(get_git_progress)\" && \
  echo -n \"\[$prompt_preposition_color\]]\")\[$prompt_reset\]\
$ "

case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

export JAVA_HOME=/data/tools/java/current
export ANT_HOME=/data/tools/apache-ant-1.8.4
export ORACLE_HOME=/data/tools/oracle/11_2

export ANT_HOME=/data/tools/apache-ant-1.8.4
export JAVA_HOME=/data/tools/java/current
export ORACLE_HOME=/data/tools/oracle/11_2
export GROOVY_HOME=/data/tools/groovy-2.3.2
export GRADLE_HOME=/data/tools/gradle-1.12
export SCALA_HOME=/data/tools/scala-2.11.1
export GOROOT=/data/tools/go

export SQLPATH=$ORACLE_HOME/bin
export LD_LIBRARY_PATH=$ORACLE_HOME/bin
